"""
Django settings for eliza_backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()


YA_PUBLIC_UPLOADER_ENDPOINT_URL = os.getenv("YA_PUBLIC_UPLOADER_ENDPOINT_URL")
YA_PUBLIC_UPLOADER_REGION_NAME = os.getenv("YA_PUBLIC_UPLOADER_REGION_NAME")
YA_PUBLIC_UPLOADER_ACCESS_KEY_ID = os.getenv("YA_PUBLIC_UPLOADER_ACCESS_KEY_ID")
YA_PUBLIC_UPLOADER_SECRET_ACCESS_KEY = os.getenv("YA_PUBLIC_UPLOADER_SECRET_ACCESS_KEY")
YA_PUBLIC_UPLOADER_BUCKET_NAME = os.getenv("YA_PUBLIC_UPLOADER_BUCKET_NAME")
YA_PUBLIC_UPLOADER_PUBLIC_BASE_URL = os.getenv("YA_PUBLIC_UPLOADER_PUBLIC_BASE_URL")

YA_PRIVATE_UPLOADER_REGION_NAME = os.getenv("YA_PRIVATE_UPLOADER_REGION_NAME")
YA_PRIVATE_UPLOADER_ACCESS_KEY_ID = os.getenv("YA_PRIVATE_UPLOADER_ACCESS_KEY_ID")
YA_PRIVATE_UPLOADER_SECRET_ACCESS_KEY = os.getenv("YA_PRIVATE_UPLOADER_SECRET_ACCESS_KEY")
YA_PRIVATE_UPLOADER_BUCKET_NAME = os.getenv("YA_PRIVATE_UPLOADER_BUCKET_NAME")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

_extra_hosts = [h.strip() for h in os.getenv("DJANGO_EXTRA_ALLOWED_HOSTS", "").split(",") if h.strip()]
ALLOWED_HOSTS = ["eliza.gallery"] + _extra_hosts

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [
    "https://eliza.gallery",
]

# Application definition

INSTALLED_APPS = [
    'main',
    'uploader',
    'catalog',
    'users',
    'chat',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'eliza_backend.middleware.RequestLogMiddleware',
]

REQUEST_LOG_FILE = BASE_DIR / 'log.txt'

ROOT_URLCONF = 'eliza_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eliza_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

AUTH_USER_MODEL = 'users.User'

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

ANYMAIL = {
    'RESEND_API_KEY': os.getenv('RESENDCOM_API_KEY'),
}

DEFAULT_FROM_EMAIL = 'noreply@otp.eliza.gallery'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'users': {'handlers': ['console'], 'level': 'INFO'},
    },
}


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static/'
MEDIA_ROOT = BASE_DIR / "media/"
MEDIA_URL = "media/"
STATICFILES_DIRS = [BASE_DIR / "static_src"]
