# Generated by Django 4.2.29 on 2026-03-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_read_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
