# Generated by Django 4.2.29 on 2026-04-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
